# Generated by Django 4.2 on 2023-04-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_generation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawnews',
            name='image_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='rawnews',
            name='original_source',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rawnews',
            name='source',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawnews',
            name='source_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
