# Generated by Django 4.2 on 2023-04-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_generation', '0003_alter_rawnews_author_alter_rawnews_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawnews',
            name='image_url',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='rawnews',
            name='original_source',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='rawnews',
            name='source_url',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
