# Generated by Django 4.2 on 2023-04-28 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_generation', '0004_alter_rawnews_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('l_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('lang', models.CharField(max_length=255)),
                ('google_lang_code', models.CharField(max_length=255)),
                ('ai4b_lang_code', models.CharField(max_length=255)),
                ('aks_lang_code', models.CharField(max_length=255)),
                ('bcp_47_lang_code', models.CharField(max_length=255)),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TranslatedArticles',
            fields=[
                ('t_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('translated_article', models.TextField(blank=True, default=None, null=True)),
                ('translated_title', models.TextField(blank=True, default=None, null=True)),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news_generation.languages')),
            ],
        ),
    ]
