# Generated by Django 4.2 on 2023-04-28 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_generation', '0006_alter_languages_ai4b_lang_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TranslatedArticles',
        ),
    ]
