# Generated by Django 4.2 on 2023-06-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_generation', '0009_videolinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemConfig',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('email_list', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
    ]
