# Generated by Django 4.2 on 2023-06-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_generation', '0010_itemconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemconfig',
            name='is_bgm_enabled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
